import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def _run_generator():
    r = subprocess.run(
        ["python3", str(REPO / "scripts" / "sync_derived.py")],
        capture_output=True, text=True, cwd=str(REPO),
    )
    assert r.returncode == 0, f"generator failed: {r.stderr}"
    return r


# ---- T4: rules -> .mdc ----

def test_generator_runs_idempotent():
    _run_generator()
    _run_generator()  # 2回目も成功（冪等）


def test_per_rule_mdc_generated():
    _run_generator()
    mdc_dir = REPO / "rules"
    for stem in ("workato-recipe-format", "workato-cli", "org-knowledge-overlay"):
        mdc = mdc_dir / f"{stem}.mdc"
        assert mdc.is_file(), f"{stem}.mdc not generated"
        head = mdc.read_text(encoding="utf-8").splitlines()
        assert head[0] == "---"
        assert any(l.startswith("description: ") for l in head[:6])
        assert any(l.startswith("alwaysApply: false") for l in head[:6])


def test_aggregate_mdc_always_apply():
    _run_generator()
    agg = REPO / "rules" / "workato-project.mdc"
    assert agg.is_file(), "aggregate workato-project.mdc not generated"
    text = agg.read_text(encoding="utf-8")
    assert "alwaysApply: true" in text.splitlines()[:8]
    assert "Workato Recipe JSON Format" in text


# ---- T5: agent -> .toml ----

def test_agent_toml_generated():
    _run_generator()
    toml = REPO / "agents" / "workato-builder.toml"
    assert toml.is_file(), "agents/workato-builder.toml not generated"
    text = toml.read_text(encoding="utf-8")
    assert text.startswith('name = "workato-builder"')
    assert "description = " in text
    assert "developer_instructions = '''" in text
    # slash -> dollar rewrite が description に効いている
    assert "$create-recipe" in text
    assert "/create-recipe" not in text


# ---- T6: context files ----

def test_context_files_generated():
    _run_generator()
    for name in ("CLAUDE.md", "AGENTS.md", "GEMINI.md"):
        f = REPO / name
        assert f.is_file(), f"{name} not generated"
        text = f.read_text(encoding="utf-8")
        assert "AUTO-GENERATED by scripts/sync_derived.py" in text
        assert "Workato Recipe JSON Format" in text
        # 旧 submodule 前提の記述が紛れ込んでいない
        assert "git submodule update --remote kit" not in text
        assert "bash kit/setup.sh" not in text


# ---- T11: drift / workflow (filled in by Task 11) ----

def test_derived_files_in_sync_with_source():
    """生成器を走らせても tracked な派生物に差分が出ない（= コミット済が最新）。"""
    _run_generator()
    r = subprocess.run(
        ["git", "status", "--porcelain",
         "rules/", "agents/", "CLAUDE.md", "AGENTS.md", "GEMINI.md"],
        capture_output=True, text=True, cwd=str(REPO),
    )
    drift = [l for l in r.stdout.splitlines()
             if l.endswith(".mdc") or l.endswith(".toml")
             or l.split()[-1] in ("CLAUDE.md", "AGENTS.md", "GEMINI.md")]
    assert not drift, f"derived files out of sync: {drift}"


def test_sync_check_workflow_exists():
    wf = REPO / ".github" / "workflows" / "sync-check.yml"
    assert wf.is_file()
    text = wf.read_text(encoding="utf-8")
    assert "scripts/sync_derived.py" in text
    assert "git diff --exit-code" in text
