import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLUGIN = REPO / "plugin"


def _run_generator():
    r = subprocess.run(
        ["python3", str(REPO / "scripts" / "sync_derived.py")],
        capture_output=True, text=True, cwd=str(REPO),
    )
    assert r.returncode == 0, f"generator failed: {r.stderr}"
    return r


def test_generator_runs_idempotent():
    _run_generator()
    _run_generator()  # 2回目も成功（冪等）


def test_agents_md_generated():
    _run_generator()
    f = PLUGIN / "AGENTS.md"
    assert f.is_file(), "plugin/AGENTS.md not generated"
    text = f.read_text(encoding="utf-8")
    assert "AUTO-GENERATED by scripts/sync_derived.py" in text
    assert "Workato Recipe JSON Format" in text
    assert "SessionStart hook" in text
    # CC-only: 他エディタ配信経路の文言は製品イントロから除去済み
    assert "Gemini via this GEMINI.md" not in text
    assert "alwaysApply .mdc" not in text
    # 旧 submodule 前提の記述が紛れ込んでいない
    assert "git submodule update --remote kit" not in text
    assert "bash kit/setup.sh" not in text


def test_generator_does_not_touch_frozen_or_root_claude_md():
    """凍結資材（.mdc/.toml/GEMINI.md）と root CLAUDE.md は生成器の対象外。"""
    _run_generator()
    r = subprocess.run(
        ["git", "status", "--porcelain",
         "plugin/rules/", "plugin/agents/", "plugin/GEMINI.md", "CLAUDE.md"],
        capture_output=True, text=True, cwd=str(REPO),
    )
    dirty = [l for l in r.stdout.splitlines()
             if l.endswith(".mdc") or l.endswith(".toml")
             or l.split()[-1] in ("plugin/GEMINI.md", "CLAUDE.md")]
    assert not dirty, f"generator touched frozen files: {dirty}"


def test_frozen_assets_still_present():
    frozen = [
        PLUGIN / "GEMINI.md",
        PLUGIN / "agents" / "workato-builder.toml",
        PLUGIN / "hooks" / "cursor.hooks.json",
        PLUGIN / "hooks" / "codex.hooks.json",
        PLUGIN / ".cursor-plugin" / "plugin.json",
        PLUGIN / ".codex-plugin" / "plugin.json",
        PLUGIN / ".codex.mcp.json",
        REPO / ".cursor-plugin" / "marketplace.json",
        REPO / ".agents" / "plugins" / "marketplace.json",
    ]
    for p in frozen:
        assert p.is_file(), f"frozen asset missing: {p}"
    mdc = list((PLUGIN / "rules").glob("*.mdc"))
    assert len(mdc) >= 10, f"frozen .mdc set incomplete: {len(mdc)}"


def test_derived_file_in_sync_with_source():
    """生成器を走らせてもコミット済みの plugin/AGENTS.md に差分が出ない。"""
    _run_generator()
    r = subprocess.run(
        ["git", "status", "--porcelain", "plugin/AGENTS.md"],
        capture_output=True, text=True, cwd=str(REPO),
    )
    assert not r.stdout.strip(), f"plugin/AGENTS.md out of sync: {r.stdout}"


def test_sync_check_workflow_pins_new_scope():
    wf = REPO / ".github" / "workflows" / "sync-check.yml"
    assert wf.is_file()
    text = wf.read_text(encoding="utf-8")
    assert "scripts/sync_derived.py" in text
    assert "git diff --exit-code" in text
    assert "plugin/AGENTS.md" in text, "drift scope must cover the new derived path"
