#!/usr/bin/env python3
"""sync_derived.py — Generate plugin/AGENTS.md from plugin/rules/*.md.

Claude Code is the only supported editor (dev/specs/2026-07-06, D1/D2), so
the single derived file is plugin/AGENTS.md — the payload injected by
plugin/bin/session-start-rules as SessionStart additionalContext.

Frozen per-editor artifacts are NOT generated or touched anymore:
plugin/rules/*.mdc, plugin/agents/*.toml, plugin/GEMINI.md, the cursor/codex
hooks variants and manifests. To revive an editor, restore its generators
from git history (scripts/sync_derived.py prior to 2026-07) and re-verify
on the real editor.

Run from repo root:  python3 scripts/sync_derived.py
CI (sync-check.yml) runs this then `git diff --exit-code` to detect drift.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = REPO_ROOT / "plugin"
RULES_DIR = PLUGIN_ROOT / "rules"


def split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter, body) where both exclude the '---' delimiters.

    The first '---' line opens the frontmatter; the next '---' line closes it.
    If the file does not start with '---', or no closing '---' is found, the
    entire text is treated as body.
    """
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        return "", text
    for i in range(1, len(lines)):
        if lines[i] == "---":
            return "\n".join(lines[1:i]), "\n".join(lines[i + 1 :])
    return "", text


def trim_trailing_newlines(text: str) -> str:
    """Mimic bash command-substitution: strip trailing newlines."""
    return text.rstrip("\n")


_HEADING_RE = re.compile(r"^(#+) ")


def demote_headings(text: str, levels: int = 1) -> str:
    """Increase the heading depth of every Markdown heading by *levels*.

    Lines inside fenced code blocks are left untouched.
    """
    out: list[str] = []
    fence = False
    for line in text.split("\n"):
        if line.startswith("```"):
            fence = not fence
            out.append(line)
            continue
        if not fence:
            m = _HEADING_RE.match(line)
            if m:
                line = ("#" * levels) + line
        out.append(line)
    return "\n".join(out)


CONTEXT_INTRO = """\
Workato development toolkit for AI coding agents. The rules below are the
always-on knowledge base for building on Workato (recipes, Workflow Apps,
AI agents, custom connectors). They are delivered automatically via the
plugin's SessionStart hook (bin/session-start-rules).

Knowledge-base documents (connectors, logic, platform, patterns) are NOT in
this file — fetch them through the docs-overlay MCP tools
`workato_docs_lookup(path)` / `workato_docs_list(prefix)` (org overrides win).
"""


def _context_body() -> str:
    parts = [
        "<!-- AUTO-GENERATED by scripts/sync_derived.py — DO NOT EDIT MANUALLY.",
        "     Source: plugin/rules/*.md -->",
        "",
        CONTEXT_INTRO,
    ]
    for src in sorted(RULES_DIR.glob("*.md")):
        _, body = split_frontmatter(src.read_text(encoding="utf-8"))
        parts.append(demote_headings(trim_trailing_newlines(body), levels=1))
        parts.append("")
    return "\n".join(parts)


def sync_context() -> None:
    out = PLUGIN_ROOT / "AGENTS.md"
    out.write_text(
        "# Workato Toolkit — Agent Context\n\n" + _context_body() + "\n",
        encoding="utf-8",
    )
    print("  ok plugin/AGENTS.md")


def main() -> None:
    sync_context()


if __name__ == "__main__":
    main()
